// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/christian-gama/pd-solucoes/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	service "github.com/christian-gama/pd-solucoes/internal/app/service/teacher"
)

// CreateTeacher is an autogenerated mock type for the CreateTeacher type
type CreateTeacher struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, input
func (_m *CreateTeacher) Handle(ctx context.Context, input *service.CreateTeacherInput) (*model.Teacher, error) {
	ret := _m.Called(ctx, input)

	var r0 *model.Teacher
	if rf, ok := ret.Get(0).(func(context.Context, *service.CreateTeacherInput) *model.Teacher); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Teacher)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *service.CreateTeacherInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCreateTeacher interface {
	mock.TestingT
	Cleanup(func())
}

// NewCreateTeacher creates a new instance of CreateTeacher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCreateTeacher(t mockConstructorTestingTNewCreateTeacher) *CreateTeacher {
	mock := &CreateTeacher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
