// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/christian-gama/pd-solucoes/internal/app/service/teacher"
	mock "github.com/stretchr/testify/mock"
)

// DeleteTeacher is an autogenerated mock type for the DeleteTeacher type
type DeleteTeacher struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, input
func (_m *DeleteTeacher) Handle(ctx context.Context, input *service.DeleteInput) error {
	ret := _m.Called(ctx, input)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service.DeleteInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewDeleteTeacher interface {
	mock.TestingT
	Cleanup(func())
}

// NewDeleteTeacher creates a new instance of DeleteTeacher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDeleteTeacher(t mockConstructorTestingTNewDeleteTeacher) *DeleteTeacher {
	mock := &DeleteTeacher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
