// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/christian-gama/pd-solucoes/internal/app/service/teacher"
	mock "github.com/stretchr/testify/mock"
)

// UpdateTeacher is an autogenerated mock type for the UpdateTeacher type
type UpdateTeacher struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, input
func (_m *UpdateTeacher) Handle(ctx context.Context, input *service.UpdateTeacherInput) (*service.FindOneTeacherOutput, error) {
	ret := _m.Called(ctx, input)

	var r0 *service.FindOneTeacherOutput
	if rf, ok := ret.Get(0).(func(context.Context, *service.UpdateTeacherInput) *service.FindOneTeacherOutput); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.FindOneTeacherOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *service.UpdateTeacherInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUpdateTeacher interface {
	mock.TestingT
	Cleanup(func())
}

// NewUpdateTeacher creates a new instance of UpdateTeacher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUpdateTeacher(t mockConstructorTestingTNewUpdateTeacher) *UpdateTeacher {
	mock := &UpdateTeacher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
