// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/christian-gama/pd-solucoes/internal/app/dto"
	mock "github.com/stretchr/testify/mock"
)

// CollegeService is an autogenerated mock type for the CollegeService type
type CollegeService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, params
func (_m *CollegeService) Create(ctx context.Context, params dto.CreateCollegeInput) (*dto.CreateCollegeOutput, error) {
	ret := _m.Called(ctx, params)

	var r0 *dto.CreateCollegeOutput
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateCollegeInput) *dto.CreateCollegeOutput); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.CreateCollegeOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateCollegeInput) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCollegeService interface {
	mock.TestingT
	Cleanup(func())
}

// NewCollegeService creates a new instance of CollegeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCollegeService(t mockConstructorTestingTNewCollegeService) *CollegeService {
	mock := &CollegeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
