// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/christian-gama/pd-solucoes/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	querying "github.com/christian-gama/pd-solucoes/internal/domain/querying"

	repo "github.com/christian-gama/pd-solucoes/internal/domain/repo"
)

// CourseSubject is an autogenerated mock type for the CourseSubject type
type CourseSubject struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, params
func (_m *CourseSubject) Create(ctx context.Context, params repo.CreateCourseSubjectParams) (*model.CourseSubject, error) {
	ret := _m.Called(ctx, params)

	var r0 *model.CourseSubject
	if rf, ok := ret.Get(0).(func(context.Context, repo.CreateCourseSubjectParams) *model.CourseSubject); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CourseSubject)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, repo.CreateCourseSubjectParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, params
func (_m *CourseSubject) Delete(ctx context.Context, params repo.DeleteCourseSubjectParams) error {
	ret := _m.Called(ctx, params)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repo.DeleteCourseSubjectParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx, params, preload
func (_m *CourseSubject) FindAll(ctx context.Context, params repo.FindAllCourseSubjectParams, preload ...string) (*querying.PaginationOutput[*model.CourseSubject], error) {
	_va := make([]interface{}, len(preload))
	for _i := range preload {
		_va[_i] = preload[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *querying.PaginationOutput[*model.CourseSubject]
	if rf, ok := ret.Get(0).(func(context.Context, repo.FindAllCourseSubjectParams, ...string) *querying.PaginationOutput[*model.CourseSubject]); ok {
		r0 = rf(ctx, params, preload...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*querying.PaginationOutput[*model.CourseSubject])
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, repo.FindAllCourseSubjectParams, ...string) error); ok {
		r1 = rf(ctx, params, preload...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindOne provides a mock function with given fields: ctx, params, preload
func (_m *CourseSubject) FindOne(ctx context.Context, params repo.FindOneCourseSubjectParams, preload ...string) (*model.CourseSubject, error) {
	_va := make([]interface{}, len(preload))
	for _i := range preload {
		_va[_i] = preload[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *model.CourseSubject
	if rf, ok := ret.Get(0).(func(context.Context, repo.FindOneCourseSubjectParams, ...string) *model.CourseSubject); ok {
		r0 = rf(ctx, params, preload...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CourseSubject)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, repo.FindOneCourseSubjectParams, ...string) error); ok {
		r1 = rf(ctx, params, preload...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, params
func (_m *CourseSubject) Update(ctx context.Context, params repo.UpdateCourseSubjectParams) (*model.CourseSubject, error) {
	ret := _m.Called(ctx, params)

	var r0 *model.CourseSubject
	if rf, ok := ret.Get(0).(func(context.Context, repo.UpdateCourseSubjectParams) *model.CourseSubject); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CourseSubject)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, repo.UpdateCourseSubjectParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCourseSubject interface {
	mock.TestingT
	Cleanup(func())
}

// NewCourseSubject creates a new instance of CourseSubject. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCourseSubject(t mockConstructorTestingTNewCourseSubject) *CourseSubject {
	mock := &CourseSubject{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
