// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/christian-gama/pd-solucoes/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	querying "github.com/christian-gama/pd-solucoes/internal/domain/querying"

	repo "github.com/christian-gama/pd-solucoes/internal/domain/repo"
)

// Course is an autogenerated mock type for the Course type
type Course struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, params
func (_m *Course) Create(ctx context.Context, params repo.CreateCourseParams) (*model.Course, error) {
	ret := _m.Called(ctx, params)

	var r0 *model.Course
	if rf, ok := ret.Get(0).(func(context.Context, repo.CreateCourseParams) *model.Course); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Course)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, repo.CreateCourseParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, params
func (_m *Course) Delete(ctx context.Context, params repo.DeleteCourseParams) error {
	ret := _m.Called(ctx, params)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repo.DeleteCourseParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx, params, preload
func (_m *Course) FindAll(ctx context.Context, params repo.FindAllCourseParams, preload ...string) (*querying.PaginationOutput[*model.Course], error) {
	_va := make([]interface{}, len(preload))
	for _i := range preload {
		_va[_i] = preload[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *querying.PaginationOutput[*model.Course]
	if rf, ok := ret.Get(0).(func(context.Context, repo.FindAllCourseParams, ...string) *querying.PaginationOutput[*model.Course]); ok {
		r0 = rf(ctx, params, preload...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*querying.PaginationOutput[*model.Course])
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, repo.FindAllCourseParams, ...string) error); ok {
		r1 = rf(ctx, params, preload...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindOne provides a mock function with given fields: ctx, params, preload
func (_m *Course) FindOne(ctx context.Context, params repo.FindOneCourseParams, preload ...string) (*model.Course, error) {
	_va := make([]interface{}, len(preload))
	for _i := range preload {
		_va[_i] = preload[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *model.Course
	if rf, ok := ret.Get(0).(func(context.Context, repo.FindOneCourseParams, ...string) *model.Course); ok {
		r0 = rf(ctx, params, preload...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Course)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, repo.FindOneCourseParams, ...string) error); ok {
		r1 = rf(ctx, params, preload...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, params
func (_m *Course) Update(ctx context.Context, params repo.UpdateCourseParams) (*model.Course, error) {
	ret := _m.Called(ctx, params)

	var r0 *model.Course
	if rf, ok := ret.Get(0).(func(context.Context, repo.UpdateCourseParams) *model.Course); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Course)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, repo.UpdateCourseParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCourse interface {
	mock.TestingT
	Cleanup(func())
}

// NewCourse creates a new instance of Course. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCourse(t mockConstructorTestingTNewCourse) *Course {
	mock := &Course{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
