// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/christian-gama/pd-solucoes/internal/app/service/student"
	mock "github.com/stretchr/testify/mock"
)

// DeleteStudent is an autogenerated mock type for the DeleteStudent type
type DeleteStudent struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, input
func (_m *DeleteStudent) Handle(ctx context.Context, input *service.DeleteInput) error {
	ret := _m.Called(ctx, input)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service.DeleteInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewDeleteStudent interface {
	mock.TestingT
	Cleanup(func())
}

// NewDeleteStudent creates a new instance of DeleteStudent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDeleteStudent(t mockConstructorTestingTNewDeleteStudent) *DeleteStudent {
	mock := &DeleteStudent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
