// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/christian-gama/pd-solucoes/internal/app/service/college"
	mock "github.com/stretchr/testify/mock"
)

// CreateCollege is an autogenerated mock type for the CreateCollege type
type CreateCollege struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, input
func (_m *CreateCollege) Handle(ctx context.Context, input *service.CreateCollegeInput) (*service.CreateOutput, error) {
	ret := _m.Called(ctx, input)

	var r0 *service.CreateOutput
	if rf, ok := ret.Get(0).(func(context.Context, *service.CreateCollegeInput) *service.CreateOutput); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.CreateOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *service.CreateCollegeInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCreateCollege interface {
	mock.TestingT
	Cleanup(func())
}

// NewCreateCollege creates a new instance of CreateCollege. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCreateCollege(t mockConstructorTestingTNewCreateCollege) *CreateCollege {
	mock := &CreateCollege{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
