// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/christian-gama/pd-solucoes/internal/app/service/college"
	mock "github.com/stretchr/testify/mock"
)

// DeleteCollege is an autogenerated mock type for the DeleteCollege type
type DeleteCollege struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, input
func (_m *DeleteCollege) Handle(ctx context.Context, input *service.DeleteCollegeInput) error {
	ret := _m.Called(ctx, input)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service.DeleteCollegeInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewDeleteCollege interface {
	mock.TestingT
	Cleanup(func())
}

// NewDeleteCollege creates a new instance of DeleteCollege. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDeleteCollege(t mockConstructorTestingTNewDeleteCollege) *DeleteCollege {
	mock := &DeleteCollege{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
