// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/christian-gama/pd-solucoes/internal/app/dto"
	mock "github.com/stretchr/testify/mock"

	querying "github.com/christian-gama/pd-solucoes/internal/domain/querying"
)

// FindAllColleges is an autogenerated mock type for the FindAllColleges type
type FindAllColleges struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, params
func (_m *FindAllColleges) Handle(ctx context.Context, params *dto.FindAllCollegesInput) (*querying.PaginationOutput[*dto.FindOneCollegeOutput], error) {
	ret := _m.Called(ctx, params)

	var r0 *querying.PaginationOutput[*dto.FindOneCollegeOutput]
	if rf, ok := ret.Get(0).(func(context.Context, *dto.FindAllCollegesInput) *querying.PaginationOutput[*dto.FindOneCollegeOutput]); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*querying.PaginationOutput[*dto.FindOneCollegeOutput])
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *dto.FindAllCollegesInput) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewFindAllColleges interface {
	mock.TestingT
	Cleanup(func())
}

// NewFindAllColleges creates a new instance of FindAllColleges. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFindAllColleges(t mockConstructorTestingTNewFindAllColleges) *FindAllColleges {
	mock := &FindAllColleges{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
