// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/christian-gama/pd-solucoes/internal/app/service/courseSubject"
	mock "github.com/stretchr/testify/mock"
)

// DeleteCourseSubject is an autogenerated mock type for the DeleteCourseSubject type
type DeleteCourseSubject struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, input
func (_m *DeleteCourseSubject) Handle(ctx context.Context, input *service.DeleteCourseSubjectInput) error {
	ret := _m.Called(ctx, input)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service.DeleteCourseSubjectInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewDeleteCourseSubject interface {
	mock.TestingT
	Cleanup(func())
}

// NewDeleteCourseSubject creates a new instance of DeleteCourseSubject. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDeleteCourseSubject(t mockConstructorTestingTNewDeleteCourseSubject) *DeleteCourseSubject {
	mock := &DeleteCourseSubject{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
