// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/christian-gama/pd-solucoes/internal/app/service/course"
	mock "github.com/stretchr/testify/mock"
)

// DeleteCourse is an autogenerated mock type for the DeleteCourse type
type DeleteCourse struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, input
func (_m *DeleteCourse) Handle(ctx context.Context, input *service.DeleteCourseInput) error {
	ret := _m.Called(ctx, input)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service.DeleteCourseInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewDeleteCourse interface {
	mock.TestingT
	Cleanup(func())
}

// NewDeleteCourse creates a new instance of DeleteCourse. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDeleteCourse(t mockConstructorTestingTNewDeleteCourse) *DeleteCourse {
	mock := &DeleteCourse{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
