// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/christian-gama/pd-solucoes/internal/app/service/subject"
	mock "github.com/stretchr/testify/mock"
)

// DeleteSubject is an autogenerated mock type for the DeleteSubject type
type DeleteSubject struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, input
func (_m *DeleteSubject) Handle(ctx context.Context, input *service.DeleteSubjectInput) error {
	ret := _m.Called(ctx, input)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service.DeleteSubjectInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewDeleteSubject interface {
	mock.TestingT
	Cleanup(func())
}

// NewDeleteSubject creates a new instance of DeleteSubject. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDeleteSubject(t mockConstructorTestingTNewDeleteSubject) *DeleteSubject {
	mock := &DeleteSubject{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
