// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/christian-gama/pd-solucoes/internal/app/service/enrollment"
	mock "github.com/stretchr/testify/mock"
)

// CreateCourseEnrollment is an autogenerated mock type for the CreateCourseEnrollment type
type CreateCourseEnrollment struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, input
func (_m *CreateCourseEnrollment) Handle(ctx context.Context, input *service.CreateCourseEnrollmentInput) (*service.Output, error) {
	ret := _m.Called(ctx, input)

	var r0 *service.Output
	if rf, ok := ret.Get(0).(func(context.Context, *service.CreateCourseEnrollmentInput) *service.Output); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.Output)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *service.CreateCourseEnrollmentInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCreateCourseEnrollment interface {
	mock.TestingT
	Cleanup(func())
}

// NewCreateCourseEnrollment creates a new instance of CreateCourseEnrollment. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCreateCourseEnrollment(t mockConstructorTestingTNewCreateCourseEnrollment) *CreateCourseEnrollment {
	mock := &CreateCourseEnrollment{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
