// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/christian-gama/pd-solucoes/internal/app/service/enrollment"
	mock "github.com/stretchr/testify/mock"
)

// DeleteCourseEnrollment is an autogenerated mock type for the DeleteCourseEnrollment type
type DeleteCourseEnrollment struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, input
func (_m *DeleteCourseEnrollment) Handle(ctx context.Context, input *service.DeleteCourseEnrollmentInput) error {
	ret := _m.Called(ctx, input)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service.DeleteCourseEnrollmentInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewDeleteCourseEnrollment interface {
	mock.TestingT
	Cleanup(func())
}

// NewDeleteCourseEnrollment creates a new instance of DeleteCourseEnrollment. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDeleteCourseEnrollment(t mockConstructorTestingTNewDeleteCourseEnrollment) *DeleteCourseEnrollment {
	mock := &DeleteCourseEnrollment{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
